/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "upaki-2s8zcbflakdmghmkpet7go3htq4": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "upaki-api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "upaki-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}